# Generated by Django 3.0.8 on 2020-07-11 18:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 11, 18, 15, 38, 35937, tzinfo=utc)),
        ),
    ]
